### ISSUE TITLE
Using scroll in as a shortcut

### ISSUE THREAD

**Issue by BenAgin1** [luerhard/kwin-walk-through-desktops#1]
Happy plasma 6! Upgraded last night and have been struggling to find a fix to my previous workflow to cycle through desktops using CTRL+ALT+[scroll]. Maybe this is a shortcoming of kwin since it seems to be kb only, but I figured I would ask here. 

In the meantime I have set it to META+` and it seems to work well. Thank you for your contribution!

The delay is a little long for my taste, will look into it if it bothers me enough.

**Comment by luerhard** [comment]
Happy, thank you for the kind words. Happy to help :)

If the delay is too long for you, there is always the option to set a shorter one.
The code of this repo should be on your computer in 

```
~/.local/share/kwin/scripts/kwin-walk-through-desktops/contents/code/main.js
```

In there, you can just change the delay (in milliseconds) in the following line:

https://github.com/luerhard/kwin-walk-through-desktops/blob/b8e4e81af12dd2444c4924056f51fc1aadcec93e/contents/code/main.js#L13

After disabling / and re-enabling the extension in your system settings, the new delay should be in place.

Sadly, I have no clue about using [scroll] in shortcuts.
